## 服务配置
server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    service:
      name: sub-project
  sleuth:
    sampler:
      # 默认0.1, 旧版本为percentage，2.0.X版本改为probability
      probability: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: test
###############################################################################
logging:
  config: classpath:logback.xml
